name: jobsearchapp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  material_design_icons_flutter: ^3.2.4096
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy.ttf

  assets:
    - assets/images/